set(CMAKE_SYSTEM_NAME Emscripten)
set(CMAKE_SYSTEM_VERSION 1)

if(NOT EMSCRIPTEN_ROOT_PATH)
    if(DEFINED ENV{EMSDK})
        set(EMSCRIPTEN_ROOT_PATH "$ENV{EMSDK}/upstream/emscripten")
    else()
        find_program(EMCC_EXECUTABLE emcc)
        if(EMCC_EXECUTABLE)
            get_filename_component(EMCC_DIR "${EMCC_EXECUTABLE}" DIRECTORY)
            get_filename_component(EMSCRIPTEN_ROOT_PATH "${EMCC_DIR}" DIRECTORY)
            message(STATUS "Found Emscripten at: ${EMSCRIPTEN_ROOT_PATH}")
        else()
            message(FATAL_ERROR "Could not find Emscripten. Please set EMSDK environment variable or install Emscripten")
        endif()
    endif()
endif()

set(CMAKE_C_COMPILER "${EMSCRIPTEN_ROOT_PATH}/bin/emcc")
set(CMAKE_CXX_COMPILER "${EMSCRIPTEN_ROOT_PATH}/bin/em++")
set(CMAKE_AR "${EMSCRIPTEN_ROOT_PATH}/bin/emar" CACHE FILEPATH "Emscripten ar")
set(CMAKE_RANLIB "${EMSCRIPTEN_ROOT_PATH}/bin/emranlib" CACHE FILEPATH "Emscripten ranlib")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(EMSCRIPTEN TRUE)
